### ISSUE TITLE
Business Detail scroll

### ISSUE THREAD

**Issue by eparadise** [code-for-chapel-hill/School-Meal-Mapper#4]
The scroll for Business Details still does not ensure all content can be displayed- this example is scrolled all the way down. In addition, some entries don't have a scroll option at all, even though not all content is visible. Any idea why?

<img width="1380" alt="Screen Shot 2020-06-18 at 1 56 20 PM" src="https://user-images.githubusercontent.com/43389857/85055454-93f2c780-b16b-11ea-882a-b11de8427989.png">

**Comment by readingdancer** [comment]
It's probably related to the size of the header, I'd bet the amount of scroll difference is the number of pixels difference between this header and the NC Covid one :)

**Comment by eparadise** [comment]
@readingdancer I'm having a hard time finding the code for the scroll. The only scrolling code I see is in ResultsList. Can you help me out?

**Comment by readingdancer** [comment]
I don't think it's related to scrolling, it's related to the size of the box it's scrolling inside. Check the size of the box and it's margins, you will probably find one that is the same sizes as the original header that needs adjusting.

**Comment by a-rothwell** [comment]
It might be because max-height doesn't take into account the padding/margin and scrolling will only occur when list length exceeds max height.

This bug appeared for me in both results list and business details

I'm not sure if using specific pixel values is a good long term fix, but the following does work

Fix: ResultsList.Vue :: Line 182

```
.resultList {
  max-height: calc(100vh - 86px);
  overflow-y: overlay;
  margin-top: 20px;
}
```

Fix:  BusinessDetails.Vue :: Line 270
```
.business-details {
  max-height: calc(100vh - 86px - 62px);
  overflow-y: auto;
  overflow-x: hidden;
}
```
